import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Geist（无衬线）和 Geist_Mono（等宽）
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"], // 仅加载拉丁字符子集
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * 配置页面标题和描述，SEO
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // antialiased 抗锯齿，使字体更平滑
      >
        {children}
      </body>
    </html>
  );
}
